fragment AuthToken on AuthTokensDto {
	accessToken
	refreshToken
	expiresIn
}

mutation Me {
	me {
		...AuthToken
	}
}

mutation RefreshTokens($refreshToken: String!) {
	refreshTokens(refreshToken: $refreshToken) {
		...AuthToken
	}
}

mutation Login($tel: String!) {
	login(tel: $tel) {
		...AuthToken
	}
}

mutation VerifyCode($verificationCode: String!) {
	verifyCode(verificationCode: $verificationCode) {
		...AuthToken
	}
}
